services:
  php:
    build: ./docker/php
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=docker-apache"
      XDEBUG_MODE: "debug"  # Включение отладки для CLI
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"